### ISSUE TITLE
How do I use the Pre-Trained Model to Answer Questions?

### ISSUE THREAD

**Issue by simonhughes22** [Pinafore/qb#20]
I did the following:
* Generate the Makefile like above
* Run make data/deep/glove.840B.300d.txt.gz to download some data

Now what do I do? How to I run the model on new data to answer questions? Thanks for making this open source, that's awesome

**Comment by ezubaric** [comment]
Everything is runnable through the Makefile.  We have example exhibition questions (what we did with Ken Jennings) in expo.csv in the data directory.  You can run that demo with ``make demo4``
