### ISSUE TITLE
How is the format of dataset?

### ISSUE THREAD

**Issue by DC-Swind** [Pinafore/qb#22]
Hi ezubaric,
I am Swind. I download the code from https://cs.umd.edu/~miyyer/qblearn/, but I have some problems when I run the script "preprocess/dparse_to_dtree.py". Based on the introduction provided by Readme file, this script is used to format the raw dataset to the format that can be fed into QANTA. 

Suppose a question has 3 sentence- S1,S2,S3 and an answer A.
The input of function "dparse" is S1,S2,S3 in a single line? (each line is a question sentence)

After run function dparse, I will get a file "raw_parses" in which each line is like "nsubj(finalized-5, john-1)".This file will use in function "process_question_file" , but there's another file 
split = cPickle.load(open('../data/correct_simlit', 'rb'))

I can not find this file and I don't know the format of this file. So can you explain the format of this file or give me an example?

Thanks a lot!
Swind

**Comment by miyyer** [comment]
You can find an example, 'correct_simscience', which should show you how the raw QA data is stored (couldn't find correct_simlit), here: http://www.cs.umd.edu/~miyyer/data/correct_simscience.pkl

The pickled object is of the form {'train': (question, answer, ID), 'test': (question, answer, ID), ...)
where each question is itself a dictionary of {0: 'this is the first sentence of the question', 1: 'this is the second sentence of the question', ..}

Also note that the sentences must be parsed in the order that you iterate over this pickled object (to associate parsed question sentences with their correct answers / question IDs). So the parses in the 'correct_literature_parses' file must be in the same order as how you iterate overcorrect_simlit.

We generated this file from our database of questions, so it's specific to our dataset. If you create a file with the same formatting, you should be able to run the process_question_file method successfully.

Hope that helps, and I apologize for the state of the preprocessing code :)
The code for the final system (in this repository) is easier to use (doesn't require parsing), so you might want to check that out as well.

Best,
Mohit

**Comment by EntilZha** [comment]
I don't know if this applies for this question, but you can see more about the data format by looking at this https://github.com/Pinafore/qb/blob/pedro/Databases.ipynb

**Comment by miyyer** [comment]
The question refers to the code for an earlier version of QANTA (2014 EMNLP paper) that isn't in this repo. But for the current version, the above link is great :)

**Comment by DC-Swind** [comment]
Thank you for your response. I solved this problem according to your prompt.

Best,
Swind

**Comment by EntilZha** [comment]
Looks resolves so closing
