### ISSUE TITLE
Error running python3 cli.py makefile

### ISSUE THREAD

**Issue by mkhooja** [Pinafore/qb#23]
I'm following the AWS installation steps and I got the following error when trying to `run python3 cli.py makefile`.  I got around it by manually downloading the "stopwords" corpora.

```
...$ python3 cli.py makefile
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/nltk/corpus/util.py", line 63, in __load
    try: root = nltk.data.find('corpora/%s' % zip_name)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/nltk/data.py", line 641, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource 'corpora/stopwords.zip/stopwords/' not found.  Please
  use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/home/ubuntu/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 4, in <module>
    from qanta.extractors import mentions
  File "/home/ubuntu/qb/qanta/extractors/mentions.py", line 12, in <module>
    from qanta.extractors.abstract import FeatureExtractor
  File "/home/ubuntu/qb/qanta/extractors/abstract.py", line 3, in <module>
    from qanta.util.constants import N_GUESSES
  File "/home/ubuntu/qb/qanta/util/constants.py", line 13, in <module>
    ENGLISH_STOP_WORDS = set(stopwords.words('english'))
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/nltk/corpus/util.py", line 99, in __getattr__
    self.__load()
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/nltk/corpus/util.py", line 64, in __load
    except LookupError: raise e
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/nltk/corpus/util.py", line 61, in __load
    root = nltk.data.find('corpora/%s' % self.__name)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/nltk/data.py", line 641, in find
    raise LookupError(resource_not_found)
LookupError:
```

**Comment by hpduong** [comment]
I've been slowly working through getting everything running locally. 
I'm having problems here, too.  

$python3 cli.py makefile

Did you download both "stopwords" and "punkt" from the GUI in nltk.download()?  Those were the required files from the previous code.

I got stuck doing the install on Arch and now I'm trying to figure things out on a Xubuntu install.  Just got through the corpora issues, myself. 

I'm now getting this error:

```
...@xubuntuAI:~/qb$ python cli.py makefile
Traceback (most recent call last):
  File "cli.py", line 4, in <module>
    from qanta.extractors import mentions
  File "/home/henry/qb/qanta/extractors/mentions.py", line 14, in <module>
    from clm.lm_wrapper import kTOKENIZER, LanguageModelBase
  File "/home/henry/qb/clm/lm_wrapper.py", line 16, in <module>
    from clm import clm
ImportError: cannot import name 'clm'

```

I think installing mcl might do the trick for that and will try it later tonight.

**Comment by mkhooja** [comment]
I ran the following from python3 to get the corpora:
```
import nltk
nltk.download("stopwords")
```
Then I got the same `ImportError: cannot import name 'clm'`.  Which I got around by replacing line 16 in lm_wrapper.py with:
```
import clm
```
Now I'm getting this error:
```
 ...$ python3 cli.py makefile
Usage: cli.py [OPTIONS] COMMAND [ARGS]...

Error: No such command "makefile".
```

**Comment by EntilZha** [comment]
A few days ago I finally merged a very large branch of work so this is probably causing some problems. I was also not quite yet done with documentation when it was advertised as ready to use so apologies.

The way to solve nltk is `python3 setup.py download`. I will make sure to document that somewhere.

The command `makefile` no longer exists since the makefile is now static. It was previously generated from a template, but `luigi` fills the role it did before as a data pipeline management system.

The import error seems odd, you may need to make sure that the `clm` targets compile from the `Makefile` which is under source control.

**Comment by EntilZha** [comment]
Also, all bug reports are appreciated. Pull requests to fix bugs or add documentation would be sweet too!

**Comment by EntilZha** [comment]
This looks resolved, if not feel free to re-open
