### ISSUE TITLE
Error on generating output/guesses.db causes dependency to be fulfilled

### ISSUE THREAD

**Issue by ezubaric** [Pinafore/qb#29]
Because it's the first real dependency people will try to build, we should not count an empty guesses.db as a completed dependency.  It will cause odd errors downstream.

Ideally, target should only get created after a successful run.  Would be good to have sanity check code to ensure that there are guesses for every question.

**Comment by EntilZha** [comment]
More generally I think that for dependencies it might be better to adopt a standard of having a `_SUCCESS` file written and check for that in addition to the actual dependency. The other change that would go along with this is to make running a target idempotent: if the target exists, but `_SUCCESS` doesn't then running the target should overwrite the old target
