### ISSUE TITLE
CreateGuesses does not write to guesses.db

### ISSUE THREAD

**Issue by ezubaric** [Pinafore/qb#31]
I'm running CreateGuesses luigi target, but the guesses.db database is created but not being populated.

The question database is non-empty
> ls -lh $QB_QUESTION_DB
> -rwxr-xr-x 1 jbg jbg 171M Jul  7 11:53 /home/jbg/repositories/qb/data/internal/questions.db

But after quite a while, the guesses database is still emtpy
> jbg@jbg-linux:~/repositories/qb$ sqlite3 $QB_GUESS_DB
> SQLite version 3.11.0 2016-02-15 17:29:24
> Enter ".help" for usage hints.
> sqlite> .tables
> guesses
> sqlite> select * from guesses;
> sqlite> 

It seems like it's waiting for input but not getting any
> DEBUG: CreateGuesses__99914b932b is currently run by worker Worker(salt=930962148, workers=10, host=jbg-linux, username=jbg, pid=2846)
> DEBUG: Asking scheduler for work...
> DEBUG: Done
> DEBUG: There are no more tasks to run at this time
> DEBUG: CreateGuesses__99914b932b is currently run by worker Worker(salt=930962148, 
> workers=10, host=jbg-linux, username=jbg, pid=2846)

Ideally, output would give clearer indication of the progress it's made and how much more there is to go.

**Comment by ezubaric** [comment]
Where should I look to debug?

**Comment by EntilZha** [comment]
Best guess is that the guess generation is still running. The relevant code is here: https://github.com/Pinafore/qb/blob/master/qanta/extract_features.py#L176-L191

I would start by putting print statements (or logging statements to leave them in permanently) before/after the `Pool` call.

**Comment by ezubaric** [comment]
Okay, stuff eventually got written, but would be good to add some indication of progress if results aren't written after 15 min.

**Comment by EntilZha** [comment]
I'll see if I can add some code for that. since it should be done on the collector of the `Pool` rather than each individual worker.

**Comment by EntilZha** [comment]
Updated to include logging https://github.com/Pinafore/qb/commit/71926c544a7825af4cca2fdb22e11b9d461e9d3e, can you give it a try and see if it works?

I should have my own system run through more later, but don't have something this minute

**Comment by ezubaric** [comment]
Yup, works fine, but should have better output to show progress.
