### ISSUE TITLE
Error while loading embeddings:

### ISSUE THREAD

**Issue by mkhooja** [Pinafore/qb#34]
As part of `make output/deep/params`, I got the following error.  I looked into the embeddings file and the problem seems to be that some terms are multi-word terms so building the embeddings array `all_vocab[word] = array(split[1:])` [here](https://github.com/Pinafore/qb/blob/master/qanta/guesser/util/load_embeddings.py#L22) is including part of the word.

Examples from data/external/deep/glove.840B.300d.txt :
```
mail：name@domain.com 0.46949 -0.5331 0.41987 0.21681 -0.4169 0.35045 0.10753 .......
is name@domain.com -0.1197 0.10706 -0.10519 -0.12412 0.4096 -0.0287 0.34704 0.3549 ...........
news:#name@domain.com 0.97894 -0.57796 0.22701 -0.81661 -0.11701 0.1271 ...........
```

Stacktrace:
```
python qanta/guesser/util/format_dan.py --threshold=5
2374
train 16276
done with  0
done with  5000
done with  10000
done with  15000
train 8845
test 3874
done with  0
test 2601
devtest 0
devtest 0
dev 16298
done with  0
done with  5000
done with  10000
done with  15000
dev 8961
python qanta/guesser/util/load_embeddings.py
loading vocab...
Traceback (most recent call last):
  File "qanta/guesser/util/load_embeddings.py", line 48, in <module>
    main()
  File "qanta/guesser/util/load_embeddings.py", line 18, in main
    all_vocab[word] = all_vocab[word].astype(float)
ValueError: could not convert string to float: 'name@domain.com'
make: *** [output/deep/params] Error 1
```

**Comment by EntilZha** [comment]
I noticed a number of errors in the embeddings file and dan pipeline in general. I moved those over to luigi as well, could you see if you get the same error after updating?

If there is still the error, its possible that getting the new embeddings file broke something. If thats the case, then I will probably provide an S3 URL to the old file if it works but the new one doesn't (I plan on testing pipeline today/tomorrow as far as I can)

**Comment by EntilZha** [comment]
PR seems to have fixed the issue
