### ISSUE TITLE
Installation wikifier2013.zip

### ISSUE THREAD

**Issue by hpduong** [Pinafore/qb#36]
Can I  have some clarification for this step:

Installation

    Download the Illinois Wikifier code (VERSION 2). Place the data directory in data/wikifier/data and put the wikifier-3.0-jar-with-dependencies.jar in the lib directory http://cogcomp.cs.illinois.edu/page/software_view/Wikifier and put the config directory in data/wikifier/config

wikifier2013.zip extracts to a wikifier2013 folder.  I've created a new wikifier folder in qb/data/ and 
placed the extracted wikifier2013 data folder there.  

`
put the wikifier-3.0-jar-with-dependencies.jar in the lib directory
`
Should I create a lib directory in qb/data/wikifier/ and place the wikifier-3.0-jar-with-dependencies.jar there?

Finally, wikifier2013.zip extracts a "configs" directory, not "config."  Should I rename the configs directory to "config" and place it in data/wikifier/ to make it data/wikifier/config?

**Comment by EntilZha** [comment]
I should update those docs to reflect new installation instructions. In the meantime, I would look at https://github.com/Pinafore/qb/blob/master/bin/bootstrap.sh to see how to place things correctly. S3 is much faster than the wikifier download for Illinois servers, but you could replace that with `wget` if needed

**Comment by EntilZha** [comment]
Docs have been updated, closing since it seems resolved
