### ISSUE TITLE
Sanity check script / integration testing

### ISSUE THREAD

**Issue by ezubaric** [Pinafore/qb#38]
A great starter project for someone trying to get up to speed on the system would be a testing setup (perhaps with Travis?  I'm not familiar enough to know if it's the right choice).  We should have tests to check:
- Everything compiles correctly, has correct types / interface
- Guesser has reasonable recall (report to group whatever it is, complain if it's too low)
- Guesser has reasonable vocabulary
- Guess database is fully populated and has recall consistent with the current set of guessers we're using
- All features are generated and none are empty
- Check classifier accuracy per category, compare to previous accuracies

**Comment by EntilZha** [comment]
I am working on this at the moment at http://leeroy.entilzha.io:8080/, but it would be great for someone else to work on making it more sophisticated.

I tried Travis and Circle CI, but they are not ideal for a few reasons (can explain if needed, but mostly not enough customization for our use case).

**Comment by EntilZha** [comment]
Closing for now since its actually quite a large task due to how many dependencies there are. In addition better reporting has been adding which alleviates some of the original need.
