### ISSUE TITLE
trained half?

### ISSUE THREAD

**Issue by Rajan** [Pinafore/qb#4]
2370(5) of	11895	Ylide	Yuan Dynasty	5
....1/5
2371(5) of	11895	Yuan Dynasty	Battle of Zama	5
....1/5
...2/5
.....3/5
2372(5) of	11895	Battle of Zama	Ziegler–Natta catalyst	6
......1/6
.....2/6
......3/6
2373(6) of	11895	Ziegler–Natta catalyst	Zollverein	7
....1/7
....2/7
....3/7
2374(7) of	11895	Zollverein	cp data/temp_guesses.db data/guesses.db
turing@ubuntu:

**Comment by ezubaric** [comment]
Thanks!  That's an output bug, not a training bug.  Some questions are being excluded and that was not accounted for in the message.  It is now resolved.

**Comment by EntilZha** [comment]
Looks resolved
