### ISSUE TITLE
Separate DAN parameters generation, training data generation, andclassifier training

### ISSUE THREAD

**Issue by EntilZha** [Pinafore/qb#40]
These three can be separate and it would make them each runnable alone.

**Comment by mkhooja** [comment]
@EntilZha: Just to confirm, are you refering to compute_vectors() in the  "training data generation" step?

**Comment by EntilZha** [comment]
That would be correct on training vectors

**Comment by EntilZha** [comment]
Looks like this is done after that PR merge.
