### ISSUE TITLE
all_sentences_buzz

### ISSUE THREAD

**Issue by Rajan** [Pinafore/qb#7]
It has taken more than 24 hours now.
What will be approximate training time for the last stage?
My config: i7 4th gen, NVIDIA Corporation GM107M [GeForce GTX 860M], 8 GB RAM
There is <5% CPU usage and ~70% memory usage. Is there something wrong?

**Comment by ezubaric** [comment]
Could you provide your console output?

**Comment by Rajan** [comment]
![screenshot from 2015-09-21 08 03 13](https://cloud.githubusercontent.com/assets/60307/9984556/50aa3f88-6037-11e5-90e4-73babffe2ca9.png)
![screenshot from 2015-09-21 08 04 24](https://cloud.githubusercontent.com/assets/60307/9984559/65e27e92-6037-11e5-9e68-d653094be151.png)

**Comment by ezubaric** [comment]
Is it not making progress?

**Comment by ezubaric** [comment]
But yes, this can take a while.

**Comment by Rajan** [comment]
Takes a few hours to process one item.

**Comment by Rajan** [comment]
Any guestimate would be useful?

**Comment by ezubaric** [comment]
It's several thousand lines per output message, so it's not that bad.  It may be too late now, but this can help:

http://www.cmcrossroads.com/article/pitfalls-and-benefits-gnu-make-parallelization

**Comment by EntilZha** [comment]
Definitely room for improvement on deep learning part, will open an issue specifically to look into how to make this faster
