### ISSUE TITLE
Setup.py Referenced in ReadMe does not exist

### ISSUE THREAD

**Issue by Nonameentered** [Pinafore/qb#83]
`python setup.py develop` and `python3 setup.py download` are both steps in the Dependencies section of the ReadMe that reference this non-existent file. 

Is this why @nhatsmrt added the spacy and nltk wordnet download info in the FAQ section and is anything else that might be missing from what used to be in setup.py? Is the absolute/relative paths issue that necessitated the `develop` line no longer relevant?

**Comment by EntilZha** [comment]
I replaced the setup.py with the poetry based install. I'm pretty sure that the download command did what Nhat documented, so probably not needed. Similarly, I think using poetry resolved the paths issue, although I'm not certain, would need to test that. If not, it would be good to figure out what the root issue is.

**Comment by GeneralPoxter** [comment]
I made a pull request updating the README to reflect this setup change.
