### ISSUE TITLE
No Requirements.txt or environment.yaml

### ISSUE THREAD

**Issue by DCRepublic** [Pinafore/qb#84]
When going to install dependencies for python `pip install -r packer/requirements.txt` references a file that does not exist. Is this temporary or should I just install all one at a time?

**Comment by EntilZha** [comment]
Everything has been swapped over to poetry-based configuration, so can update readme to match that (e.g., `poetry install` and using `poetry run stuff` or `poetry shell` to activate environment).

**Comment by DCRepublic** [comment]
Thank you!

 Is there any other way to download the external datasets other than the `./dataset.py download ` command? When trying to use the other commands like `./dataset.py download wikidata` it gives me an error that dataset.py does not take any other arguments besides download. I really need to obtain the `qanta.torchtext` dataset.
