### ISSUE TITLE
Missing dependencies for qanta training

### ISSUE THREAD

**Issue by GeneralPoxter** [Pinafore/qb#87]
While trying to train the RNN guesser, I had downloaded the qanta dataset and set up the virtual environment through "poetry install". In the virutal environment, I ran the luigi command for DownloadData, and 3 Wikipedia tasks were completed successfully while the NLTKDownload() task was left pending due to a missing external dependency.

I understand that the current documentation does not correspond to a poetry setup, but I made sure to download wordnet, stopwords, average perceptron tagger, and punkt to the default directory that is in nltk.data.path, so I'm not sure what exactly the missing external dependencies are in this case.

**Comment by GeneralPoxter** [comment]
Adding the file "data/external/nltk_download_SUCCESS" seems to fix the issue: https://github.com/Pinafore/qb/blob/43bf4243bb6116827343248b702826ea0944a076/setup.py#L58

**Comment by EntilZha** [comment]
Yes, this used to be done via a command like `python setup.py download` that would download the required nltk data (pretty certain punkt) and then create an empty file (nltk_download_SUCCESS) to indicate that the data was downloaded.

**Comment by GeneralPoxter** [comment]
I made a pull request that adds this as part of the setup process

**Comment by GeneralPoxter** [comment]
Pull request merged.
