### ISSUE TITLE
TypeError: load_vectors() got an unexpected keyword argument 'unk_init'

### ISSUE THREAD

**Issue by NPSDC** [Pinafore/qb#89]
When trying to run the models using luigi calling AllGuesserReports, I get the following error;

`TypeError: load_vectors() got an unexpected keyword argument 'unk_init'`. Also attaching the screenshot. Any suggestions what I might be doing wrong would be appreciated.

[
![error](https://user-images.githubusercontent.com/12257696/114802674-1d632e00-9d6c-11eb-9a8e-ae37db25b7c6.png)
](url)

**Comment by EntilZha** [comment]
(meta note, its easier to copy/paste text in code blocks than read screenshots)

Could you give information about which versions of packages you have installed? My first instinct is that our code relies on an older version of torchtext and if you are using a new version then the arguments might not match.

**Comment by NPSDC** [comment]
The version I am using for torchtext `0.2.3` and for pytorch `0.3.0`. Are there any other package versions that I can provide?

**Comment by GeneralPoxter** [comment]
Ah if it's pytorch 0.2.3, then the existing code before mergin my pull request should work. Problem was, I got my dependencies through the pyproject.toml and poetry.lock files, which specified pytorch 1.7.1 or something. See [here](https://github.com/NVIDIA/flownet2-pytorch/issues/113#issuecomment-450802359).
