### ISSUE TITLE
StopIteration error halts training for Python ^3.7

### ISSUE THREAD

**Issue by GeneralPoxter** [Pinafore/qb#92]
While trying to train the rnn guesser, I encountered the following error:
```
ERROR: [pid 8772] Worker Worker(salt=781876901, workers=1, host=poxter, username=poxter, pid=8772) failed    TrainGuesser(guesser_module=qanta.guesser.rnn, guesser_class=RnnGuesser, dependency_module=qanta.pipeline.guesser, dependency_class=EmptyTask, config_num=0)
Traceback (most recent call last):
  File "/home/poxter/.cache/pypoetry/virtualenvs/qanta-virId68h-py3.9/lib/python3.9/site-packages/torchtext/data/iterator.py", line 182, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/poxter/.cache/pypoetry/virtualenvs/qanta-virId68h-py3.9/lib/python3.9/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/home/poxter/.cache/pypoetry/virtualenvs/qanta-virId68h-py3.9/lib/python3.9/site-packages/luigi/worker.py", line 133, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/poxter/qb/qanta/pipeline/guesser.py", line 42, in run
    guesser_instance.train(qb_dataset.training_data())
  File "/home/poxter/qb/qanta/guesser/rnn.py", line 311, in train
    train_acc, train_loss, train_time = self.run_epoch(train_iter)
  File "/home/poxter/qb/qanta/guesser/rnn.py", line 334, in run_epoch
    for batch in iterator:
RuntimeError: generator raised StopIteration
```
This is connected to the [custom torchtext package](https://github.com/EntilZha/text) used by the pyproject.toml, and specifically, these [lines of code](https://github.com/EntilZha/text/blob/cddf59085e137d95e8c3b7f57840ef48f1bcb6b8/torchtext/data/iterator.py#L181-L182).

This [StackOverflow post](https://stackoverflow.com/a/51701040/14218946) explains the issue regarding StopIteration for Python versions 3.7 and up.

I made changes in my own [fork](https://github.com/GeneralPoxter/text) according to the [corresponding lines](https://github.com/pytorch/text/blob/ba0bf52fd0f7981407ec7479918a5d34b00d2211/torchtext/legacy/data/iterator.py#L161-L162) in the current torchtext repo. On my system, these changes seem to fix the issue.

**Comment by Mshivam2409** [comment]
@GeneralPoxter Heyyy! The clone you've made is of torchtext 0.9.1,however for me the repo only works on legacy versions i.e. <=0.8. (It raises some `unk` errors for me as in #89 ). Otherwise we need to make changes in qanta `torchtext.data` -> `torchtext.legacy.data` !

**Comment by keithcallenberg** [comment]
Changing that line in iterator.py fixes the issue on my system too.

**Comment by EntilZha** [comment]
Could you make a pull request to fix this for everyone?

**Comment by GeneralPoxter** [comment]
I made a modification to the pyproject.toml changing the source repo to my fork of your fork, since it appears that I cannot make pull requests directly to your fork.
